let member key j = Result.fold (Json.mem j key) ~ok:(fun x -> x) ~error:(fun e -> `String (Err.show e))
let invoke () = Json.obj [
  ("VDeploymentVdSpec", Value.json (V_deployment.marshal_spec (V_deployment.vd_spec_default ())));
  ("VDeploymentT", Dynamic_object.to_json (V_deployment.marshal (V_deployment.default ())));
  ("VStatefulSetT", Dynamic_object.to_json (V_stateful_set.marshal (V_stateful_set.default ())));
  ("VreplicaSetVrsSpec", Value.json (Vreplica_set.marshal_spec (Vreplica_set.vrs_spec_default ())));
  ("VreplicaSetVrsStatus", Value.json (Vreplica_set.marshal_status (Some (Vreplica_set.vrs_status_default ()))));
  ("VreplicaSetT", Dynamic_object.to_json (Vreplica_set.marshal (Vreplica_set.default ())));
  ("AffinityT", Affinity.to_json (Affinity.default ()));
  ("ApiMethodPreconditions", let p = Api_method.preconditions_default () in Json.obj_opt [("uid", Json.opt (fun x -> Json.int_ (Common.Uid.to_int x)) p.uid); ("resourceVersion", Json.opt (fun x -> Json.int_ (Common.Resource_version.to_int x)) p.resource_version)]);
  ("ContainerExecAction", Container.exec_action_to_json (Container.exec_action_default ()));
  ("ContainerTcpSocketAction", Container.tcp_socket_action_to_json (Container.tcp_socket_action_default ()));
  ("ContainerLifecycleHandler", Container.lifecycle_handler_to_json (Container.lifecycle_handler_default ()));
  ("ContainerLifecycle", Container.lifecycle_to_json (Container.lifecycle_default ()));
  ("ContainerContainerPort", Container.container_port_to_json (Container.container_port_default ()));
  ("ContainerVolumeMount", Container.volume_mount_to_json (Container.volume_mount_default ()));
  ("ContainerEnvVarSource", Container.env_var_source_to_json (Container.env_var_source_default ()));
  ("ContainerEnvVar", Container.env_var_to_json (Container.env_var_default ()));
  ("ContainerProbe", Container.probe_to_json (Container.probe_default ()));
  ("ContainerSecurityContext", Container.security_context_to_json (Container.security_context_default ()));
  ("ContainerT", Container.to_json (Container.default ()));
  ("DeploymentStrategyT", Deployment_strategy.to_json (Deployment_strategy.default ()));
  ("LabelSelectorT", Label_selector.to_json (Label_selector.default ()));
  ("LocalObjectReferenceT", Local_object_reference.to_json (Local_object_reference.default ()));
  ("ObjectFieldSelectorT", Object_field_selector.to_json (Object_field_selector.default ()));
  ("ObjectMetaT", Object_meta.to_json (Object_meta.default ()));
  ("OwnerReferenceT", Owner_reference.to_json (Owner_reference.default ()));
  ("PersistentVolumeClaimSpec", Persistent_volume_claim.spec_to_json (Persistent_volume_claim.spec_default ()));
  ("PersistentVolumeClaimStatus", Persistent_volume_claim.status_to_json (Persistent_volume_claim.status_default ()));
  ("PersistentVolumeClaimT", Dynamic_object.to_json (Persistent_volume_claim.marshal (Persistent_volume_claim.default ())));
  ("PodSecurityContextT", Pod_security_context.to_json (Pod_security_context.default ()));
  ("PodSpecT", Pod_spec.to_json (Pod_spec.default ()));
  ("PodTemplateSpecT", Pod_template_spec.to_json (Pod_template_spec.default ()));
  ("ResourceRequirementsT", Resource_requirements.to_json (Resource_requirements.default ()));
  ("TolerationT", Toleration.to_json (Toleration.default ()));
  ("ConfigMapT", Dynamic_object.to_json (Config_map.marshal (Config_map.default ())));
  ("PodT", Dynamic_object.to_json (Pod.marshal (Pod.default ())));
  ("StatefulSetOrdinals", member "ordinals" (Stateful_set.ss_spec_to_json { (Stateful_set.ss_spec_default ()) with ordinals = Some (Stateful_set.ordinals_default ()) }));
  ("StatefulSetRollingUpdate", member "rollingUpdate" (member "updateStrategy" (Stateful_set.ss_spec_to_json { (Stateful_set.ss_spec_default ()) with update_strategy = Some { (Stateful_set.update_strategy_default ()) with rolling_update = Some (Stateful_set.rolling_update_default ()) } })));
  ("StatefulSetUpdateStrategy", member "updateStrategy" (Stateful_set.ss_spec_to_json { (Stateful_set.ss_spec_default ()) with update_strategy = Some (Stateful_set.update_strategy_default ()) }));
  ("StatefulSetRetentionPolicy", member "persistentVolumeClaimRetentionPolicy" (Stateful_set.ss_spec_to_json { (Stateful_set.ss_spec_default ()) with persistent_volume_claim_retention_policy = Some (Stateful_set.retention_policy_default ()) }));
  ("StatefulSetSsSpec", Stateful_set.ss_spec_to_json (Stateful_set.ss_spec_default ()));
  ("StatefulSetSsStatus", Stateful_set.ss_status_to_json (Stateful_set.ss_status_default ()));
  ("StatefulSetT", Dynamic_object.to_json (Stateful_set.marshal (Stateful_set.default ())));
  ("VolumeKeyToPath", Volume.key_to_path_to_json (Volume.key_to_path_default ()));
  ("VolumeConfigMapProjection", Volume.config_map_projection_to_json (Volume.config_map_projection_default ()));
  ("VolumeSecretProjection", Volume.secret_projection_to_json (Volume.secret_projection_default ()));
  ("VolumeVolumeProjection", Volume.volume_projection_to_json (Volume.volume_projection_default ()));
  ("VolumeProjectedVolumeSource", Volume.projected_volume_source_to_json (Volume.projected_volume_source_default ()));
  ("VolumeDownwardApiVolumeFile", Volume.downward_api_volume_file_to_json (Volume.downward_api_volume_file_default ()));
  ("VolumeDownwardApiVolumeSource", Volume.downward_api_volume_source_to_json (Volume.downward_api_volume_source_default ()));
  ("VolumeHostPathVolumeSource", Volume.host_path_volume_source_to_json (Volume.host_path_volume_source_default ()));
  ("VolumeConfigMapVolumeSource", Volume.config_map_volume_source_to_json (Volume.config_map_volume_source_default ()));
  ("VolumeSecretVolumeSource", Volume.secret_volume_source_to_json (Volume.secret_volume_source_default ()));
  ("VolumeEmptyDirVolumeSource", Volume.empty_dir_volume_source_to_json (Volume.empty_dir_volume_source_default ()));
  ("VolumePersistentVolumeClaimVolumeSource", Volume.persistent_volume_claim_volume_source_to_json (Volume.persistent_volume_claim_volume_source_default ()));
  ("VolumeT", Volume.to_json (Volume.default ()));
  ("VolumeResourceRequirementsT", Volume_resource_requirements.to_json (Volume_resource_requirements.default ()));
]
