"""Emit concrete Kanon layouts and structural equality from the reviewed schema.

The checked-in output is the library source. This generator never executes or
translates controller behaviour and rejects unknown types or dependency cycles.
"""
import json
from pathlib import Path
import re

root = Path(__file__).resolve().parent.parent
schema = json.loads((root / "model-schema.json").read_text())
nodes = {(d["module"], d["type"]): d for d in schema}
done = {("value", "t")}
active = set()
out = ["-- Generated by scripts/generate-model.py from model-schema.json.",
       "-- Layouts and equality only. Behaviour lives in separate modules."]
exports = []
erased_types = {"Unit"}
compiled_schema = {}

def camel(s):
    return "".join(part[:1].upper() + part[1:] for part in s.split("_") if part)

def name(module, typ):
    return camel(module) + ("T" if typ == "t" else camel(typ))

def lower(s):
    return s[:1].lower() + s[1:]

def emit(text):
    out.append(text)

def both(checks):
    acc = "true"
    for check in reversed(checks):
        acc = f"boolAnd ({check}) ({acc})"
    return acc

def list_type(typ, eq):
    n = "List" + re.sub(r"[^A-Za-z0-9]", "", typ)
    if n in done:
        return n, lower(n) + "Equal"
    done.add(n)
    compiled_schema[n] = {"kind": "list", "element": typ}
    f = lower(n)
    emit(f"mu {n} : Type 0 :=\n| {f}Nil : {n}\n| {f}Cons (head : {typ}) (tail : {n}) : {n}")
    emit(f"def {f}Empty : {n} := {f}Nil")
    emit(f"def {f}Push : {typ} -> {n} -> {n} := fun (h : {typ}) (t : {n}) => {f}Cons h t")
    emit(f"def rec {f}Length : {n} -> Nat := fun (xs : {n}) =>\n"
         f"  match xs as self in {n} return Nat with | {f}Nil => 0 | {f}Cons h t => natAdd 1 ({f}Length t)")
    emit(f"def rec {f}Equal : {n} -> {n} -> Bool := fun (xs : {n}) (ys : {n}) =>\n"
         f"  match xs as self in {n} return Bool with\n"
         f"  | {f}Nil => natEq ({f}Length ys) 0\n"
         f"  | {f}Cons h t =>\n"
         f"    match ys as other in {n} return Bool with\n"
         f"    | {f}Nil => false\n"
         f"    | {f}Cons x rest =>\n"
         f"      case ({eq} h x) with | 0 (u : Unit) => false | 1 (u : Unit) => {f}Equal t rest")
    emit(f"def rec {f}Nth : {n} -> Nat -> Option ({typ}) := fun (xs : {n}) (i : Nat) =>\n"
         f"  match xs as self in {n} return Option ({typ}) with\n"
         f"  | {f}Nil => none ({typ})\n"
         f"  | {f}Cons h t =>\n"
         f"    case (natEq i 0) with | 1 (u : Unit) => some ({typ}) h | 0 (u : Unit) => {f}Nth t (natSub i 1)")
    exports.extend([f + "Empty", f + "Push", f + "Length"])
    return n, f + "Equal"

def resolve(module, typ):
    typ = typ.strip()
    if typ.endswith(" option"):
        inner, eq = resolve(module, typ[:-7])
        return f"Option ({inner})", f"optionEqual ({inner}) ({eq})"
    if typ.endswith(" list"):
        return list_type(*resolve(module, typ[:-5]))
    if typ.endswith(" result"):
        match = re.fullmatch(r"\((.+), (.+)\) result", typ)
        if not match:
            raise ValueError(f"Unsupported result: {typ}")
        a, ae = resolve(module, match[2])
        b, be = resolve(module, match[1])
        return f"Either ({a}) ({b})", f"eitherEqual ({a}) ({b}) ({ae}) ({be})"
    primitives = {"string": ("Bytes", "bytesEqual"), "int": ("Int", "intEqual"),
                  "bool": ("Bool", "boolEqual"), "unit": ("Ghost", "ghostEqual"),
                  "string Smap.t": ("StringMap", "stringMapEqual"),
                  "Common.Uid.t": ("Int", "intEqual"),
                  "Common.Resource_version.t": ("Int", "intEqual"),
                  "Value.t": ("Value", "valueEqual"), "Yojson.Safe.t": ("Value", "valueEqual")}
    if typ in primitives:
        return primitives[typ]
    mod, member = (typ.split(".", 1) if "." in typ else (module, typ))
    mod = mod[:1].lower() + mod[1:]
    generate(mod, member)
    n = name(mod, member)
    return n, lower(n) + "Equal"

def generate(module, typ):
    key = module, typ
    if key in done:
        return
    if key in active:
        raise ValueError(f"Recursive dependency: {key}")
    active.add(key)
    d = nodes[key]
    body = d["body"]
    n = name(module, typ)
    f = lower(n)
    if body.startswith("{"):
        fields = [field.split(":", 1) for field in body[1:-1].split(";") if field.strip()]
        fields = [(k.strip(), *resolve(module, t)) for k, t in fields]
        compiled_schema[n] = {"kind": "record", "source": d["source"], "module": module,
                              "fields": [[k, t] for k, t, _ in fields]}
        emit(f"-- Source: {d['source']} type {typ}.")
        args = " ".join(f"(f{i} : {t})" for i, (_, t, _) in enumerate(fields))
        binders = " ".join(f"f{i}" for i in range(len(fields)))
        emit(f"mu {n} : Type 0 :=\n| mk{n} {args} : {n}")
        emit(f"def {f}Make : {' -> '.join(t for _, t, _ in fields)} -> {n} := fun {args} => mk{n} {binders}")
        exports.append(f + "Make")
        checks = []
        for i, (field, t, eq) in enumerate(fields):
            getter = f + camel(field)
            emit(f"def {getter} : {n} -> {t} := fun (o : {n}) =>\n"
                 f"  match o as self in {n} return {t} with | mk{n} {binders} => f{i}")
            replacement = " ".join("value" if j == i else f"f{j}" for j in range(len(fields)))
            emit(f"def {f}Set{camel(field)} : {t} -> {n} -> {n} := fun (value : {t}) (o : {n}) =>\n"
                 f"  match o as self in {n} return {n} with | mk{n} {binders} => mk{n} {replacement}")
            checks.append(f"{eq} ({getter} a) ({getter} b)")
            if t not in erased_types:
                exports.append(getter)
            exports.append(f + "Set" + camel(field))
        emit(f"def {f}Equal : {n} -> {n} -> Bool := fun (a : {n}) (b : {n}) => {both(checks)}")
    elif body.startswith("|"):
        variants = []
        for v in body.split("|")[1:]:
            parts = v.strip().split(" of ", 1)
            variants.append((parts[0], None if len(parts) == 1 else resolve(module, parts[1])))
        compiled_schema[n] = {"kind": "enum", "source": d["source"],
                              "variants": [[v, None if p is None else p[0]] for v, p in variants]}
        emit(f"-- Source: {d['source']} type {typ}.")
        emit(f"mu {n} : Type 0 :=\n" + "\n".join(
            f"| {f}{camel(v)}" + ("" if payload is None else f" (value : {payload[0]})") + f" : {n}"
            for v, payload in variants))
        emit(f"def {f}Rank : {n} -> Nat := fun (v : {n}) =>\n"
             f"  match v as self in {n} return Nat with\n" + "\n".join(
                 f"  | {f}{camel(v)}" + ("" if p is None else " x") + f" => {i}"
                 for i, (v, p) in enumerate(variants)))
        arms = []
        for i, (v, p) in enumerate(variants):
            if p is None:
                expression = f"natEq ({f}Rank b) {i}"
            else:
                expression = f"(match b as other in {n} return Bool with " + " ".join(
                    f"| {f}{camel(w)}" + ("" if q is None else " y") + " => " +
                    (f"{p[1]} x y" if j == i else "false") for j, (w, q) in enumerate(variants)) + ")"
            arms.append(f"  | {f}{camel(v)}" + ("" if p is None else " x") + f" => {expression}")
            ctor = f + camel(v)
            wrapper = ctor + "Value"
            emit(f"def {wrapper} : " + (n + f" := {ctor}" if p is None else
                 f"{p[0]} -> {n} := fun (x : {p[0]}) => {ctor} x"))
            exports.append(wrapper)
        emit(f"def {f}Equal : {n} -> {n} -> Bool := fun (a : {n}) (b : {n}) =>\n"
             f"  match a as self in {n} return Bool with\n" + "\n".join(arms))
        exports.append(f + "Rank")
    else:
        underlying, eq = resolve(module, body)
        compiled_schema[n] = {"kind": "alias", "source": d["source"], "type": underlying}
        if underlying in erased_types:
            erased_types.add(n)
        emit(f"def {n} : Type 0 := {underlying}")
        emit(f"def {f}Equal : {n} -> {n} -> Bool := fun (a : {n}) (b : {n}) => {eq} a b")
    done.add(key)
    active.remove(key)

for module, typ in nodes:
    generate(module, typ)
(root / "src/model.kan").write_text("\n\n".join(out) + "\n")
(root / "model-exports.json").write_text(json.dumps(exports, indent=2) + "\n")
(root / "layout-info.json").write_text(json.dumps(compiled_schema, indent=2) + "\n")
print(f"Generated {len(nodes)} source types, {len(exports)} ABI accessors")
